# -*- coding: utf-8 -*-
"""TxtToImg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179mnq7FNouiJEUtQ2odqxDmKkEEsZnUs
"""

pip install diffusers transformers accelerate safetensors torch

from diffusers import StableDiffusionPipeline
import torch

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
).to("cuda")

# text prompt
prompt = "farmer in field"

import matplotlib.pyplot as plt

image = pipe(prompt).images[0]
plt.imshow(image)
plt.axis('off')
plt.show()